from tweet import *
at= []
at.append(Tweet("Play my super challenging rhythm game Rhythmopolis on https://gamejolt.com/games/Rhythmopolis/295396 #gamedev #indiedev #indiegame", "images/rhythmopolis_1.png"))
at.append(Tweet("#ThisIsMadness \nNo, This is bunny! https://gamejolt.com/games/feedthebunny/300422  #gamedev #indiedev", "images/feedthebunny.png"))
at.append(Tweet("A small open world puzzle game created with #rpgmaker . Play 'Carpe Diem' at https://gamejolt.com/games/carpe-diem/30132 #indiegame", "images/carpediem.png"))
at.append(Tweet("BOOM! Frenzy two player #retro #arcade action with Bomberman. https://gamejolt.com/games/bomberman/30497 #gamedev", "images/bomberman.png"))
at.append(Tweet("Over 1000 different items available in #rpg #indiegame Schrotbeton: http://ludumdare.com/compo/ludum-dare-28/?action=preview&uid=29172", "images/schrotbeton.jpg"))
at.append(Tweet("The bold walking simulator features a beautiful #pixelart walking #animation https://gamejolt.com/games/boldwalksimulator/274553\n#gamedev #indiedev #indiegame", "images/bold.gif"))
at.append(Tweet("#minimalistic #towerdefense #td created in one hour #1hgj defend against crusaders https://gamejolt.com/games/dac/296547 ", "images/defenders_gif.gif"))
at.append(Tweet("Complete and utter nonsense is a fast paced #arcade #indiegame created for #1hgj http://gamejolt.com/games/complete-nonsense/232383", "images/nonsense.gif"))
at.append(Tweet("Let's get this started: Play Pneumochute: #pixelart by @xXBloodyOrange, best overall for Gameinfection Hackathon #indiegame https://gamejolt.com/games/pneumochute/287471", "images/pneumochute_jumpdown.gif"))
at.append(Tweet("How good is your reaction? How fast can you click? #indiedev #indiegame: Mouse Click https://gamejolt.com/games/mouseclick/173964", "images/reaction.gif"))
at.append(Tweet("Evade the falling blocks! #minimal #indiegame #1hgj #gamedev https://gamejolt.com/games/theroom/276326", "images/room.gif"))
at.append(Tweet("Two player #arcade #couch action in Lords of Ice and Fire! https://gamejolt.com/games/lords-of-ice-and-fire/102409 \n#haxe #haxeflixel #gamedev #indiedev #indiegame #2d #pixelart", "images/lordsOfIceAndFire.gif"))
at.append(Tweet("No matter how cool you are, you will never be as cool as those penguins who take part in an epic fight between Ice and Fire https://gamejolt.com/games/lords-of-ice-and-fire/102409 ", "images/lords_penguins.gif"))
